# Generated by Django 5.2.7 on 2025-11-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersurvey',
            name='emotion_intensity',
            field=models.IntegerField(choices=[(1, '1점 (매우높음/편함/잘됨)'), (2, '2점'), (3, '3점 (보통)'), (4, '4점'), (5, '5점 (매우낮음/불편/안됨)')], default=3, verbose_name='3. 오늘 느낀 긍정적 감정의 강도'),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='energy_level',
            field=models.IntegerField(choices=[(1, '1점 (매우높음/편함/잘됨)'), (2, '2점'), (3, '3점 (보통)'), (4, '4점'), (5, '5점 (매우낮음/불편/안됨)')], default=3, verbose_name='2. 오늘 에너지 수준'),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='focus_level',
            field=models.IntegerField(choices=[(1, '1점 (매우높음/편함/잘됨)'), (2, '2점'), (3, '3점 (보통)'), (4, '4점'), (5, '5점 (매우낮음/불편/안됨)')], default=3, verbose_name='6. 오늘 집중이 잘 된 정도'),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='goal_achievement',
            field=models.IntegerField(choices=[(1, '1점 (매우높음/편함/잘됨)'), (2, '2점'), (3, '3점 (보통)'), (4, '4점'), (5, '5점 (매우낮음/불편/안됨)')], default=3, verbose_name='7. 오늘 목표 달성 정도'),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='self_care_satisfaction',
            field=models.IntegerField(choices=[(1, '1점 (매우높음/편함/잘됨)'), (2, '2점'), (3, '3점 (보통)'), (4, '4점'), (5, '5점 (매우낮음/불편/안됨)')], default=3, verbose_name='5. 나를 위해 한 행동에 대한 만족도'),
        ),
    ]
