# Generated by Django 5.2.7 on 2025-11-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_usersurvey_emotion_intensity_usersurvey_energy_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersurvey',
            name='mood_score',
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='relationship_discomfort_score',
            field=models.IntegerField(choices=[(1, '1점 (매우높음/편함/잘됨)'), (2, '2점'), (3, '3점 (보통)'), (4, '4점'), (5, '5점 (매우낮음/불편/안됨)')], default=1, verbose_name='4. 관계에서의 불편함 수준'),
        ),
    ]
